edge-classic/EDGE-classic

CMakeLists.txt, source_files/libpng/arm/arm_init.c, source_files/libpng/pngrutil.c
Apple Silicon fixes for libpng.
Since M1 ARM chips are a bit special (they are neither cortex, armv etc..) they use neon a bit differently than libpng currently allows (it only seems to support arm chips on Linux/Windows rather than M1 Macs).  The CMakeFiles adds a definition on Apple Silicon computers so it will bypass the offending code, on Intel Macs, it will execute normally.
=> libpng fixes for M1 build

source_files/edge/w_texture.cc
Been gettting this error lately in several pwads. Changing it to a warning seems to not cause any ill effects.
=> Changed an error to a warning

source_files/edge/p_user.cc
We need at least 1 sprite in a weapons states, even if it's an invisible dummy png.
Unfortunately up to now EDGE gave the user no clue why certain weapons could never be selected.
=> Add warning for weapons with no sprites

source_files/edge/w_sprite.cc
Try to fix cases where some dumbass used A1 instead of A0 for a sprite with no rotations
=> Hack for incorrect sprite naming

source_files/ddf/level.cc, source_files/ddf/level.h, source_files/edge/f_interm.cc
LEAVING_BACKGROUND and
ENTERING_BACKGROUND which can be used to override the intermission background defined in games.ddf on a per level basis.
=> New levels.ddf commands

source_files/edge/f_interm.cc
If we have a custom mapname graphic e.g.CWILVxx then use that
=> Intermission screen uses custom mapname GFX if available

source_files/edge/f_interm.cc
If we have custom graphics for mapnames, "Entering" or "Finished" then they will be used instead of text strings.
Also improved positioning of these screen elements.
=> Intermission screen cleanup

source_files/ddf/thing.cc, source_files/ddf/thing.h, source_files/edge/p_spec.cc
Similar to the same in attacks.ddf. 
Monsters flagged with this special cannot activate special lines i.e. doors etc.
=> NO_TRIGGER_LINES special for things.ddf

source_files/edge/p_spec.cc
Boaty MacBoatwad map07 has an erroneous skytransfer
=> SKYTRANSFER null check

source_files/edge/s_music.cc, source_files/opl/midifile.cc, source_files/opl/midifile.h
I mucked up the previous check, apologies for that, MIDI files have a"MThd" magic at the very beginning and that's the more standard way to check.
This PR also replaces the "ssize_t" in the OPL midi loader with "size_t" type.  I will keep in mind that Microsoft compilers don't know about "ssize_t".
I tested these changes and both seem good.
=> check first for bytes to detect MIDI

source_files/ddf/main.cc
This directive does nothing, so we may as well just ignore it.
=> ignore the `#VERSION` directive in DDF files.

source_files/edge/p_spec.cc
For example, a 128x128 texture will be half scale when the line length is 64, and double scale when the line length is 256.
=> changed flat scaling linedefs (810-825) to take image size into account.

source_files/ddf/level.cc, source_files/ddf/level.h, source_files/ddf/line.cc, source_files/edge/dm_defs.h, source_files/edge/e_main.cc, source_files/edge/g_game.cc, source_files/edge/p_setup.cc, source_files/edge/sv_glob.cc
These do almost nothing nowadays, the only remaining effect is a translation of unknown sector specials in the range 0-99 to the range 4400-4499, which was needed by some ancient EDGE mods (way back in the mists of time).
=> removed `-ecompat` cmdline option, disabled BOOM_COMPAT level flag.

source_files/ddf/thing.cc, source_files/dehacked/deh_frames.cc
This compensates for the fact that EDGE always executes the action in the initial (spawn) state of a newly created object, but Doom/BOOM/MBF do not.
=> DEH_EDGE : output a SPAWN state which does not execute the initial action

source_files/edge/p_setup.cc
Worked for things spawned via RTS.
But not for things already present in the map.
=> MOBJs with a TAG now supported

source_files/edge/p_setup.cc
This is a valid scenario, a map with a single sector and a simple shape (e.g. a square) does not need any BSP partitioning.
=> fixed XGL3 loader to allow a map with no nodes.

source_files/edge/f_interm.cc, source_files/edge/hu_draw.cc, source_files/edge/hu_draw.h, source_files/edge/vm_coal.cc, source_files/edge/vm_coal.h, source_files/edge/vm_hud.cc, source_files/edge/w_pk3.cc, source_files/edge/w_wad.cc, source_files/edge/w_wad.h
Also mad the default (zero) have behavior compatible with existing COAL huds,which is to extend the area to the full width of the screen when left and right touch edge of virtual 320x200 screen.
=> support `flags` parameter for hud.render_world() and hud.render_automap().

source_files/edge/vm_player.cc
For some reason "Shells" seem to return a weapon obj which caused a crash. Now explicitly check it's a BENEFIT_weapon too
=> Bugfix: query_weapon()

source_files/ddf/language.cc
At some stage AddOrReplace was changed so that it only ever stored 1 single language ref.
=> Bugfix: UMAPINFO

source_files/edge/p_local.h, source_files/edge/p_map.cc
Added LINE_PARTS= as an alternative method of assigning the texture to use instead of
BROKEN_TEXTURE=.
We can now use LINE_PARTS= to take it directly from the map linedef i.e. LINE_PARTS=RIGHT_LOWER; to use the linedefs front lower texture.
=> GLASS linetype: improvement

CHANGELOG.txt, source_files/edge/p_inter.cc
Now it will simply subtract from current health and not behave like DAMAGE_PLAYER (which reduces armour, causes pain states, respects immunity / resistence / invulnerable / immortal etc).
=> Changed how LOSE_BENEFIT HEALTH is handled in RTS

CHANGELOG.txt, source_files/edge/p_setup.cc
The IWAD for Doom2 has a bug in MAP05 where 2 sectors are incorrectly tagged 9.  This fixes it properly and finally ;)
=> Doom2 Map05 bug fix

.github/workflows/cmake.yml, CMakeLists.txt, source_files/ajbsp/CMakeLists.txt, source_files/coal/CMakeLists.txt, source_files/crsid/CMakeLists.txt, source_files/ddf/CMakeLists.txt, source_files/dehacked/CMakeLists.txt, source_files/ec_voxelib/CMakeLists.txt, source_files/edge/CMakeLists.txt, source_files/epi/CMakeLists.txt, source_files/fluidlite/CMakeLists.txt, source_files/fmmidi/CMakeLists.txt, source_files/glad/CMakeLists.txt, source_files/libymfm/CMakeLists.txt, source_files/m4p/CMakeLists.txt, source_files/miniz/CMakeLists.txt, source_files/ymfmidi/CMakeLists.txt
Here are some improvements to the CMake scripts for review.  This PR addresses issues I ran into with the upcoming web build and is also a step towards making the build a bit more unified/configurable. 
The main changes being:
1) Use MSVC instead of WIN32 in conditionals, and silencing some of MSVC's more obnoxious warnings, at least until can get a better handle on the more significant ones. 
2)  Removing the number of conditionals in general by grouping them where possible 
3) Consolidate redundant compiler settings and remove optimization level settings which should be handled by the various **CMAKE_BUILD_TYPE** build types, such as **Debug**, **Release**, **RelWithDebInfo** and **MinSizeRel**.  There is still room for massaging these a bit, should really look into what CMake is …
=> CMake Improvements

CHANGELOG.txt, source_files/edge/vm_player.cc
COAL player.query_weapon() would not return ZOOM FACTOR in some cases.
=> COAL player.query_weapon() fix

CHANGELOG.txt, source_files/edge/p_local.h, source_files/edge/p_weapon.cc, source_files/edge/rad_act.cc
For the rts REPLACE_WEAPON command and the weapon.ddf BECOME() action: If current ammo is bigger than the new clip size, reduce current ammo to new clip size.
=> Fix for Weapon clip/ammo

source_files/ddf/thing.cc
Wads with a DEHACKED player entry had crouching/jumping deactivated as the defaults were set to 0.
=> Added default crouch and jump values

CMakeLists.txt, source_files/xxhash/xxhash.hpp
Fixes xxhash.hpp when compiling under gcc in debug.  Introduces an "EDGE_DEBUG" preprocessor which can be used to detect debug builds across platforms
=> Fix debug gcc build with xxhash.hpp

source_files/edge/vm_player.cc
Made it so that a player slightly over the edge of a drop off, or between 2 raised floors, is not considered on the ground.
=> COAL tweak: player.on_ground()

.github/workflows/cmake.yml, CMakeLists.txt, source_files/edge/CMakeLists.txt
This PR:
1) Removes generator specific conditionals in favor or platform/toolchain ones
2) Adds logging to cmake in actions so can better debug what is happening on Actions
3) Generates a list of files to copy post edge-classic build, and only copies them if different.  This also now uses a single custom command rather than multiple
4) Switches actions to use MSYS Makefiles generator for now, due to what I think is a weird quoting issue with the Ninja generator:
Ninja: 
```
cmd.exe /C "cd /D D:\a\EDGE-classic\EDGE-classic\build\source_files\edge && D:\a\_temp\msys64\mingw32\bin\cmake.exe -E copy_if_different D:/a/EDGE-classic/EDGE-classic/build/source_files/edge/edge-classic.exe /mingw32/bin/SDL2.dll /mingw32/bin/libgcc_s_dw2-1.dll /mingw32/bin/libstdc++-6.dll …
```
=> Improve cmake conditionals and post build file copying

source_files/edge/defaults.h, source_files/edge/e_input.cc, source_files/edge/e_input.h, source_files/edge/e_main.cc, source_files/edge/i_ctrl.cc, source_files/edge/i_ctrl.h, source_files/edge/i_video.cc, source_files/edge/m_menu.cc, source_files/edge/m_menu.h, source_files/edge/m_misc.cc, source_files/edge/m_misc.h, source_files/edge/m_option.cc, source_files/edge/p_mobj.cc, source_files/edge/p_mobj.h, source_files/edge/p_spec.h, source_files/edge/r_main.cc, source_files/edge/r_things.cc, source_files/edge/s_blit.cc, source_files/edge/s_blit.h, source_files/edge/s_music.cc, source_files/edge/s_music.h, source_files/edge/s_sound.h
The idea is to have more flexibility for things like (in this first case) mouse sensitivity. The previous implementation had an integer value which was an index into a preset array of floating-point values. I've also added generic functions for updating a CVAR value from an options menu item, thereby reducing the amount of redundant functions whose only purpose was to update a certain CVAR.
=> Slider rework + sliders that can hold floating-point values

source_files/edge/p_setup.cc
The compiler was warning about -Wdelete-incomplete, which also showed up under address sanitizing as a runtime issue upon delete.
/mnt/c/Dev/EDGE-classic/source_files/edge/p_setup.cc: In function ‘void LoadThings(int)’:
/mnt/c/Dev/EDGE-classic/source_files/edge/p_setup.cc:689:18: warning: deleting ‘const void*’ is undefined [-Wdelete-incomplete]
delete[] data;
=> Fix issue with undefined deletes

.vscode/launch.json
This just moves the windows debugger back to be first in list in VSCode, kinda wish it would detect which toolchain you are using and only show the relevant debugger.  Maybe there is a property setting for that...
=> Move windows debug to be first in VSCode

edge_defs/scripts/coal_api.ec, source_files/edge/vm_player.cc
Returns the light level in the current sector
=> New COAL command: player.sector_light()

edge_base/blasphemer/scripts/coal_hud.ec, edge_base/heretic/scripts/coal_hud.ec, edge_defs/scripts/coal_hud.ec
Some widescreen statusbars were displaying wrong.
=> Fix: Ignore STBAR and BARBACK offsets

cmake/Emscripten.cmake, source_files/coal/c_memory.h, source_files/edge/p_setup.cc, source_files/epi/endianess.h
This fixes some alignment issues when running under the web platform with SAFE_HEAP defined, and under linux/gcc using asan.  It should also address the arm32 hack when loading nodes.   I went with GetU32LE instead of GetLEU32, for example because the later boggles my eyes.  
Basically, it is undefined behavior to deference a pointer cast from an incompatible alignment.  Some architectures tolerate this, others bomb depending on how the load falls, which can seem "random" 
Tested with Comatose wad under MSVC and GCC, on linux, web, and windows platforms.
=> Fix some alignment issues

source_files/ddf/thing.cc, source_files/ddf/thing.h
Given a door key flag, returns the corresponding mobjtype. For cases were a  custom key thing has been created in DDF with a different name i.e. "Rune key" has a BLUE_SKULL pickup benefit.
=> New method: LookupDoorKey()

edge_defs/scripts/lines.ddf
1. Dummy sector with desired brightness.
2. Tag one of the lines and give it this type.
3. Any other lines with the same tag will use this brightness even if the rest of the sector is pitch black.
=> New Linetype: [850] Bright wall

CHANGELOG.txt, source_files/edge/p_mobj.cc
GLASS lines were not working with projectiles if no EFFECT_OBJECT was defined.
=> BUG: our breakable walls were not working with projectiles

source_files/edge/rad_act.cc
Causes assert errors if we pickup stuff too fast. We can uncomment again if it causes issues
=> Don't do the blockmap checks for now

CHANGELOG.txt, source_files/edge/p_action.cc, source_files/edge/rad_act.cc
Old pre-EC legacy issue: map AMBUSH flag was being lost if mobj was being replaced during gameplay via BECOME. Was also now affecting new EC commands i.e. UNBECOME/MORPH/UNMORPH ddf commands or REPLACE_THING rts command.
=> Legacy bug: map AMBUSH flag was being lost

source_files/edge/vm_hud.cc
Avoid possible CTD with null refs if using any player.xxx commands in the load_level hook.
=> COAL: avoid possible CTD

source_files/ddf/thing.cc, source_files/edge/am_map.cc
Fix for missing DDF entry for key. Only ZombieTC causes this. Instead of erroring out, just log it and  gracefully show nothing.
=> Automap: Keyinfo error

.vscode/launch.json
Use the default of "internalConsole" when debugging in VSCode, which is consistent with Linux setting in json, and avoids leaving a bunch of terminal windows with "Press any key to continue..."
=> Use default of internalConsole when debugging

CHANGELOG.txt, source_files/edge/p_map.cc
pre-EC legacy issue: crushed monsters never entered their GIB states
=> Bug fix: crushed monsters never entered their GIB states

CHANGELOG.txt, source_files/edge/p_action.cc
Auto-aim now targets "fuzzy" monsters i.e. Specters.
"Fixed" against my will ;)
=> Auto-aim now targets "fuzzy" monsters

source_files/edge/defaults.h, source_files/edge/m_misc.cc, source_files/edge/m_option.cc, source_files/edge/r_image.cc, source_files/edge/r_image.h, source_files/edge/r_md2.cc, source_files/edge/r_mdl.cc, source_files/edge/r_shader.cc, source_files/edge/r_texgl.cc, source_files/edge/r_things.cc, source_files/edge/r_voxel.cc
Tried to make Detail Level behavior more consistent and meaningful:
1 - More sensible max texture sizes and unlinked max size from texture being mipmappable
2 - Tied previously independent mipmap setting to Detail Level
3 - Made number of extra modulate passes provided by Detail Level consistent regardless of unit source
4 - Enabled dlights to work at "Low" Detail Level using minimum number of passes
5 - Moved Detail Level option to Performance Options menu to reflect that it is more of a thing to manipulate if one is resource-constrained as opposed to pure aesthetics like Smoothing/Upscaling
Unrelated:
Renamed "HQ2x" setting to "Upscale Textures" per earlier conversations and added help text
=> Detail Level Updates

edge_defs/scripts/coal_api.ec, source_files/edge/vm_player.cc
This allows us to play a generic sound if no corresponding flats.ddf entry exists
=> COAL: player.play_footstep() now returns 0 if unsuccessful

source_files/edge/dm_data.h, source_files/edge/m_option.cc, source_files/edge/p_inter.cc, source_files/edge/p_map.cc, source_files/edge/p_mobj.cc, source_files/edge/p_setup.cc, source_files/edge/p_spec.cc
Remove toggle; added linedef bit 11 flag from Eternity for solving issues with older maps. Will wadfix/otherwise address other map issues if/when encountered.
=> Unconditionally enable MBF21 lines/sectors

source_files/ddf/game.cc, source_files/ddf/game.h, source_files/edge/m_menu.cc
Added an optional boolean option NO_SKILL_MENU to Games.ddf. When set to TRUE, skill menu is skipped after episode selection (or after "new game" is selected if there's only one episode) and game starts immediately with skill set to 2 ("Hurt me plenty"). Useful for creating Quake-like skill selection levels using RTS, or when you just don't want to have skill levels in your game.
=> Added NO_SKILL_MENU boolean option to Games.ddf

source_files/ddf/thing.cc, source_files/ddf/thing.h, source_files/edge/e_player.cc
Added "EXACT_" optional prefix to RTS's ON_CONDITION flag.
Returns true only when value exactly matches the value in brackets (unlike the default "greater or equal").
Should be mostly useful with counters, but can also be used to trigger something when player has exactly 4 shells/30 health/50 armor/etc left.
Works with all numerable conditions: health, armour, ammo, power (seconds left), inventory and counter.
Examples:
ON_CONDITION EXACT_AMMO2(4)
ON_CONDITION EXACT_HEALTH(25)
=> Added "EXACT_" optional prefix to RTS's ON_CONDITION flag

CHANGELOG.txt, source_files/ddf/thing.cc, source_files/ddf/thing.h, source_files/edge/p_action.cc, source_files/edge/p_action.h, source_files/edge/p_inter.cc, source_files/edge/p_mobj.cc, source_files/edge/p_mobj.h, source_files/edge/sv_mobj.cc
THINGS.DDF:
- New Action command: SET_PAINCHANCE(percentage) which will dynamically change a monsters painchance. Possible usage: if we do SET_PAINCHANCE(0%) at the start of a lengthy PAIN state, this will make sure the whole animation is played out and won't be interrupted by another shot which would normally make us re-start the pain animation again. Remember to set it back to normal at the end of the lengthy animation.
- New Special flag: IMMOVABLE which will make this thing be unaffected by thrust from attack impacts irrespective of whether it has a small MASS or a very large one.
=> THINGS.DDF: SET_PAINCHANCE() action and IMMOVABLE flag

source_files/edge/p_local.h, source_files/edge/p_map.cc, source_files/edge/p_mobj.cc, source_files/edge/p_spec.cc
Replaced usage of P_SpawnBlood() with a new dedicated function for spawing debris.
=> Fix: Breaking glass influenced by Blood menu

CHANGELOG.txt, source_files/edge/p_action.cc
SKULLFLY attacks that cause zero damage no longer make victim enter painstate. Bullet and missile behaviour seems consistent with this so did the same for skullfly attacks.
=> Bugfix: SKULLFLY zero damage causes pain

CHANGELOG.md, edge_defs/scripts/lines.ddf
Fixed Autoscale texture linetypes(855,856,857) and Brightwall(850) being USEable (repeatedly) by the player.
=> BUGFIX: several new linetypes incorrectly defined

source_files/edge/p_action.cc, source_files/edge/rad_act.cc
Since we added Scaling and Aspect to MOBJ (for UDMF reasons), we need to update them when using BECOME/MORPH actions.
=> Bugfix: Scaling/Aspect not being respected with BECOME/MORPH

CHANGELOG.md, source_files/edge/script/compat/lua_hud.cc, source_files/edge/vm_hud.cc
Fixed COAL/Lua functions hud.get_image_width() and hud.get_image_height() never returning 0 if image does not exist. They were instead always returning the dummy image size if the requested image did not exist.
=> Bugfix: hud.get_image_width() and hud.get_image_height()

CHANGELOG.md, source_files/edge/p_user.cc, source_files/edge/p_weapon.cc
- Autoswitch to a new weapon even if the clip is not full.
- Missing the 3rd and 4th clip defaults being applied when getting a weapon.
=> Weapon tweaks

CHANGELOG.md, source_files/ddf/ddf_thing.cc, source_files/ddf/ddf_thing.h, source_files/edge/p_spec.cc
Will allow this thing to use teleports even if NO_TRIGGER_LINES is set. i.e. you want a dog that cannot open a door, but can teleport for example ;)
=> Things.ddf: new Special flag: TRIGGER_TELEPORTS

CHANGELOG.md, source_files/edge/rad_trig.cc
Fixed multiple RTS scripts with the same tag not running simultaneously: we were only running the first one basically.
Now we no longer use linked list lookups, but instead just run through all scripts as the overhead is neglible and the old way was prone to issues.
=> Fixed multiple RTS scripts with the same tag.

CHANGELOG.md, edge_defs/scripts/colmap.ddf, source_files/ddf/ddf_style.cc, source_files/ddf/ddf_style.h, source_files/edge/hu_style.cc
STYLES.DDF: able to add a dropshadow effect to TEXT, ALT, TITLE, HELP, HEADER or SELECTED strings via 2 new sub-commands
- .DROPSHADOW_COLOURMAP = [colourmap];
- .DROPSHADOW_OFFSET = [float];
=> New STYLES.DDF dropshadow effect

source_files/ddf/ddf_thing.cc, source_files/edge/p_action.cc, source_files/edge/p_action.h
Changes the objects visual scale. This does not affect the actual collision box and is mainly intended for special effects things, such as a puff of smoke gradually dissipating by expansion (in combination with TRANS_FADE) or  shrinking and disappearing.
=> New DDF action: SET_SCALE(float)

CMakeLists.txt, libraries/stb/stb_vorbis.h, source_files/edge/f_finale.cc, source_files/edge/p_action.cc, source_files/edge/w_epk.cc
This PR fixes the current warnings under MSVC.  The only thing not sure on is removing `-D_STATIC_CPPLIB`, as this was giving deprecated warnings from the STL here, and causing link failures.  It seemed to work fine without it.
=> Fix MSVC warnings

source_files/edge/e_input.cc, source_files/edge/e_main.cc, source_files/edge/hu_draw.cc, source_files/edge/m_cheat.cc, source_files/edge/p_setup.cc, source_files/edge/r_main.cc, source_files/edge/r_md2.cc, source_files/edge/r_mdl.cc, source_files/edge/r_sky.cc, source_files/edge/s_blit.cc
These are fairly niche and also relatively invasive versus other cheats (directly altering rendering, input and sound mixing functions; altering the levels as they are processed via p_setup, etc). Would be nice if they could come back as scriptable and less 'hardcoded' solutions in the future.
=> Remove fliplevels/goobers cheats

source_files/edge/defaults.h, source_files/edge/e_main.cc, source_files/edge/i_ctrl.cc, source_files/edge/i_video.cc, source_files/edge/i_web.cc, source_files/edge/m_option.cc, source_files/edge/r_modes.cc, source_files/edge/r_modes.h
For things like the web player, eventual migration to SDL3, and other factors, it makes less sense to try to continue to support exclusive fullscreen mode. This makes Windowed and Borderless Fullscreen the only available screen modes.
=> Remove Exclusive Fullscreen mode

source_files/ddf/ddf_attack.cc, source_files/ddf/ddf_thing.cc, source_files/ddf/ddf_thing.h, source_files/edge/e_main.cc, source_files/edge/p_action.cc, source_files/edge/p_blockmap.cc, source_files/edge/p_mobj.cc, source_files/edge/r_render.cc, source_files/edge/r_shader.cc, source_files/edge/rad_act.cc
This removes the second dlight that could be defined for map objects; most places in the code didn't seem to account for it at all (referencing only index 0 instead of both 0 and 1). This also reduces the potential for even more rendering passes per thing.
=> Remove "DLIGHT2" DDF special and associated code

source_files/edge/r_backend.cc, source_files/edge/r_backend.h, source_files/edge/r_bsp.cc, source_files/edge/r_render.cc, source_files/edge/r_render.h, source_files/edge/render/gl/gl_units.cc, source_files/edge/render/sokol/sokol_units.cc
This entirely decouples rendering from the BSP traversal.  It also adds a render unit locking mechanism which guards render unit generation around critical sections.  In case someone tries to add rendering code outside of where it should be :)  This is key for multithreading bsp traversal and render unit generation.
=> Sokol: Add render unit locking and isolate rendering from BSP traversal

source_files/edge/r_render.cc, source_files/edge/r_render.h, source_files/edge/r_things.cc, source_files/edge/r_things.h
Alpha masked polygons do not need to be depth sorted unlike blended ones.  This fixes that assumption and greatly reduces the number of DrawSubsector on the transparent list.  It also means that things which are not actually transparent do not need to be sorted in their subsector.
=> Rendering: Make alpha mask part of solid rendering pass

source_files/edge/r_state.h, source_files/edge/render/gl/gl_state.cc, source_files/edge/render/gl/gl_units.cc
While consolidating the render state and such, I tossed out a bit of texture/environment tracking that ended up causing a regression in performance when using the legacy GL render path. This restores the active_tex/active_env tracking in RenderCurrentUnits for legacy GL while leaving the Sokol path untouched.
=> Fix performance regression in legacy GL r_units code

source_files/edge/render/gl/gl_md2.cc, source_files/edge/render/gl/gl_mdl.cc
This restores the state reset that is now necessary after restoring the old r_units behavior for legacy GL
=> Restore GL state reset (legacy path) after drawing models

CHANGELOG.md, source_files/edge/p_action.cc
MLOOK_TURN and MLOOK_FACE thing.ddf actions were exactly the same. 
Changed MLOOK_TURN to behave like it's horizontal equivalent TURN.
=> FIX: MLOOK_TURN and MLOOK_FACE were identical

CHANGELOG.md, source_files/ddf/ddf_weapon.cc, source_files/edge/p_action.cc, source_files/edge/p_action.h, source_files/edge/p_weapon.cc
-MLOOK_TURN() and MLOOK_FACE() thing.ddf actions were exactly the same. Now MLOOK_TURN() affects horizontal and MLOOK_FACE() affects vertical.
- Changed FACE() thing.ddf action to behave like it's horizontal equivalent TURN().
=> Consolidation of MLOOK_xxx, TURN and FACE actions

source_files/edge/r_image.cc, source_files/edge/r_image.h, source_files/edge/w_epk.cc, source_files/epi/epi_ename.h
I was waiting upwards of 40 seconds for some maps to load in debug, making debugging features pretty slow to iterate on.  This gets that time down to a couple seconds, and also greatly improves level load time of complex maps in release builds.
=> Speed up level loads by improving texture lookups

source_files/edge/render/gl/gl_md2.cc, source_files/edge/render/gl/gl_mdl.cc, source_files/edge/render/sokol/sokol_md2.cc, source_files/edge/render/sokol/sokol_mdl.cc
Restores the tilt interpolation that https://github.com/edge-classic/EDGE-classic/commit/9b11f4d4a262bc3f3a8b17b558f0b5d8c736ef77 removed, but only for weapons; there was a lot of jitter otherwise.
=> Revert previous model interpolated tilt fix for player weapons only

libraries/miniaudio/ma_reverb_node.cc, libraries/miniaudio/ma_reverb_node.h, libraries/miniaudio/miniaudio.cc, libraries/miniaudio/verblib.h, source_files/edge/i_sound.cc, source_files/edge/i_sound.h, source_files/edge/m_misc.cc, source_files/edge/m_option.cc, source_files/edge/p_user.cc, source_files/edge/s_blit.cc, source_files/edge/s_blit.h, source_files/edge/s_sound.cc
This implements a more robust reverb than the faux delay-based method we were using previously. Not only can the parameters be more finely tuned, but it is easier to make "stronger" reverb without hitting feedback loops and other distortions that the delay nodes was causing at higher settings.
I've also switched the simple on/off toggle in the Sound Options menu to be None/Headphones/Speakers, with "Headphones" being a more subtle setting (especially indoor reverb in relation to room size) versus "Speakers", which is a stronger setting that carries across easier over a sound bar/external speakers/etc
=> Add verblib-based reverb node for Dynamic Reverb

source_files/dehacked/deh_frames.cc
Fixes https://github.com/edge-classic/EDGE-classic/issues/768 and most likely other Dehacked patches that we haven't caught yet
=> Fix MBF21/DSDehacked state marking/allocation

source_files/edge/r_sky.cc
Fixes https://github.com/edge-classic/EDGE-classic/issues/769
=> Tweak sky fog density when using Vanilla sky stretch option

CMakeLists.txt, source_files/edge/am_map.cc, source_files/edge/con_con.cc, source_files/edge/i_video.cc, source_files/edge/n_network.cc, source_files/edge/n_network.h, source_files/edge/p_enemy.cc, source_files/edge/r_bsp.cc, source_files/edge/r_effects.cc, source_files/edge/r_render.cc, source_files/edge/r_things.cc, source_files/edge/r_wipe.cc, source_files/edge/render/gl/gl_md2.cc, source_files/edge/render/gl/gl_mdl.cc, source_files/edge/render/sokol/sokol_md2.cc, source_files/edge/render/sokol/sokol_mdl.cc
This removes the "uncapped_frames" CVAR and sets all behavior as if it was enabled. Additionally, this will set the Sokol render path as the default, with a platform-appropriate backend selected (D3D11/GLES3/GL) unless the EDGE_LEGACY_GL CMake option is set to ON. Sokol backend preferences passed to CMake will be respected as well (i.e., specifying the GLES3 backend on a platform that would normally default to GL, etc).
=> Renderer Default Updates

source_files/edge/r_sky.cc, source_files/edge/render/gl/gl_units.cc
This fixes the following issues with sky fog:
- Legacy GL renderer was still using a minimum threshold for fog density (instead of checking AlmostEquals for not being 0.0f), causing sky fog to be disabled as it wasn't meeting said threshold
- Sky fog densities have been adjusted per renderer to be consistent with each other
=> Sky fog density fixes

source_files/coal/c_local.h
Addresses https://github.com/edge-classic/EDGE-classic/issues/883
=> Revert COAL memory blocks to use char instead of double

source_files/edge/am_map.cc, source_files/edge/am_map.h, source_files/edge/hu_draw.cc, source_files/edge/hu_draw.h, source_files/edge/r_misc.cc, source_files/edge/r_units.h, source_files/edge/render/sokol/sokol_units.cc
This strives to improve the performance of the automap, which in very complex maps (especially when cheating via IDDT) can bottleneck easily, with the following changes:
- BSP-based seg walk replaced with iteration of mapped linedefs (or all linedefs + things if cheating) while clipping to the automap frame boundary
- As a side effect, the "automap_debug_bsp" CVAR and its functionality have been removed
- Automap lines are grouped into buckets for batch rendering based on line width to reduce render state changes
- Sokol rendering now uses quads for line drawing instead of triangle strips
- (Incidental) fixes for interpolation of collision debug bounding boxes and when map rotation is enabled
=> Automap Rendering Improvements

source_files/ddf/ddf_types.h, source_files/dehacked/deh_things.cc, source_files/dehacked/deh_weapons.cc, source_files/edge/p_action.cc, source_files/edge/p_weapon.cc
This is a rollup of various fixes for things observed when playing the "Intro" episode of [Hardfest III](https://www.doomworld.com/forum/topic/151578-rc2-hardfest-3/):
- Removed auto-assigning of DoomEd numbers to DEHEXTRA mobjs (fixed certain monsters in the monster gallery being replaced by their projectile attack projectiles due to colliding IDs)
- Added default "ammo per shot" for weapons if they were not otherwise specified (fixed the chainsaw replacement/ultra rocket launcher being able to fire with zero ammunition)
- A_EffectTracker will now use the ARCHVILE_FIRE DDFATK definition if the mobj does not have a current attack specified (fixed the jump orbs dying but not launching the player upward or damaging them)
- Replaced use of MobjSetDirectionAndSpeed with simply setting the new …
=> Fix MBF21 issues discovered with Hardfest III

edge_base/chex1/scripts/language.ldf, edge_defs/scripts/language.ldf, source_files/edge/e_main.cc, source_files/edge/m_cheat.cc, source_files/edge/m_menu.cc, source_files/edge/m_option.cc
This removes the usage of printf format specifiers in DDFLANG entries; obituaries still have things like %o and %k but these are parsed in an obituary-specific function and not passed on verbatim to printf
=> Remove printf format specifiers from DDFLANG entries

source_files/edge/p_action.cc
Restores a setting of the projectile angle that was accidentally dropped when implementing the OFFSETS_LAST and Z_OFFSET DDFATK specials
=> Fix projectile angle in DoLaunchProjectile for non-MBF21 projectiles

source_files/edge/p_telept.cc
This matches Boom behavior and fixes some situations in which things were being teleported to the wrong line
=> Disregard lines without a back sector in FindTeleportLine

source_files/ddf/ddf_attack.cc, source_files/ddf/ddf_main.cc
A thing whose DDFTHING entry has been modified from the default may no longer have things like a CHASE state, so instead of being a fatal error attempt to fall back to the spawn state in these cases. This function is only used during the AttackCleanUp function when parsing DDF, so should hopefully have minimal impact.
=> Add fallback for DDFATK entries that spawn a thing which has been modified

source_files/edge/p_inter.cc, source_files/edge/p_mobj.cc, source_files/edge/p_mobj.h, source_files/edge/p_telept.cc, source_files/edge/p_user.cc, source_files/edge/sv_mobj.cc
This makes the following changes to our existing mikoportal implementation:
- Applies to any mobj, not just voodoo dolls
- Will not cause the "falling player" scream to be played
- Allows "peccaflight" (https://www.doomworld.com/forum/topic/143370-achieving-flight-in-vanilla-boom-etc-a-new-technique) to be achieved if negative Z momentum reaches a certain threshold in a mikoportal sector
Compared to the vanilla peccaflight implementation, the player will always have at least a limited degree of air control
=> Improve mikoportals/implement peccaflight

source_files/edge/p_mobj.cc
This fixes the ability to accumulate X/Y momentum by running against a door/wall/etc. The most obvious example of this behavior was CJ's Wolf3D mod where the player would "shoot" into the next room if they are running against a horizontal sliding door while it is opening.
=> Fix momentum accumulation in P_XYMovement

libraries/opalmidi/opal.cpp, source_files/edge/i_movie.cc, source_files/edge/i_sound.cc, source_files/edge/s_blit.cc, source_files/edge/s_blit.h, source_files/edge/s_flac.cc, source_files/edge/s_m4p.cc, source_files/edge/s_midi.cc, source_files/edge/s_midi_ec.cc, source_files/edge/s_mp3.cc, source_files/edge/s_ogg.cc, source_files/edge/s_sound.cc
This makes the following fixes/tweaks to audio stuff:
- OPL emulation output volume better matches SF2/Fluidlite output
- SFX/Music max gain increased
- Attenuation model fixed for sound effects playing "in-world", now using linear attenuation and the traditional S_CLOSE_DIST and S_CLIPPING_DIST values (200/1200)
- Boss monsters are now attenuated based on "in-world" position
- Unlike regular sounds, they use the exponential attenuation model so that they are not completely silenced
- Will still play at full volume regardless of the 'VOLUME' special in DDFSFX
- Reduced max sound channels from 256 to 32 pending other miniaudio work
=> Adjust miniaudio sound/music params

.github/workflows/cmake.yml, CMakeLists.txt, libraries/miniaudio/miniaudio.cc
Add CI coverage for "legacy" oriented builds that disable newer rendering and memory management options
=> Update CMake/add CI for MinGW32+Legacy GL+No Mimalloc

source_files/ddf/ddf_thing.cc, source_files/ddf/ddf_weapon.cc, source_files/edge/p_mobj.cc, source_files/edge/p_spec.cc, source_files/edge/r_defs.h, source_files/edge/sv_level.cc
Made it easier to determine if carry scrollers are meant to be constant vs. proportional; flipped x offsets provided by MBF21 codepointers to match DDF behavior
=> Fix Dehacked-provided x offsets and Boom carry scrollers

source_files/ddf/ddf_attack.cc, source_files/ddf/ddf_thing.cc, source_files/ddf/ddf_thing.h, source_files/dehacked/deh_things.cc, source_files/edge/p_action.cc, source_files/edge/p_mobj.cc
This fixes the BORE special so that it does not continue to damage the same mobj within the same tic, as well as decoupling Dehacked projectile damage from explosion damage which fixes radius issues with A_Detonate
=> Fixes for Dehacked-related explosions and BORE special

source_files/edge/am_map.cc, source_files/edge/hu_draw.cc
This fixes the graphic/text key overlays mentioned in https://github.com/edge-classic/EDGE-classic/issues/935
This was a result of the automap lines now using raw screen coordinates instead of HUD coordinates, which was throwing off the HUD drawing functions when it came time to do the overlay
=> Fixes for automap key graphic/text overlays

source_files/edge/i_movie.cc, source_files/edge/s_flac.cc, source_files/edge/s_mp3.cc, source_files/edge/s_ogg.cc, source_files/edge/s_sound.cc
This adds some missing NO_PITCH flags and also adjusts the sound attenuation behavior to be closer to pre-Miniaudio parameters
=> Adjust Miniaudio SFX attenuation/flags

source_files/ddf/ddf_level.cc, source_files/ddf/ddf_level.h, source_files/ddf/ddf_main.cc, source_files/edge/p_map.cc, source_files/edge/p_spec.cc, source_files/edge/r_render.cc, source_files/edge/r_sky.cc, source_files/edge/r_sky.h, source_files/edge/s_blit.h
Bumps sound channel limit to 128, tweaks some plane mover and BOOM line transfer details, and implements sky scrolling via DDFLEVEL and Boom sky transfers. DDFLEVL syntax is SKY_SCROLL_X and SKY_SCROLL_Y as percentage of the texture's width/height per tic to scroll
NOTE: Sky scrolling is only applied to 'fake' (single-texture) skies, not true skyboxes
=> Sound channel/plane mover/BOOM line fixes; implement sky scrolling

source_files/ddf/ddf_thing.cc
Inverted xoffset when fixing MBF21 weapon/projectile attacks; this is actually wrong for A_SpawnObject
=> Fix xoffset for A_SpawnObject

source_files/edge/r_sky.cc
The horizontal scrolling component should be much smaller than I thought
=> Adjust horizontal scroll speed for Boom sky transfers

source_files/ddf/ddf_states.cc, source_files/ddf/ddf_states.h, source_files/dehacked/deh_frames.cc, source_files/dehacked/deh_info.cc, source_files/dehacked/deh_info.h, source_files/dehacked/deh_things.cc, source_files/edge/p_action.cc, source_files/edge/p_mobj.cc
This fixes A_MonsterBulletAttack not playing the mobj's attack sound when firing, as well as a handful of the new thing flags not being applied as intended. Additionally, implemented the SKILL5FAST frame flag, and generally opened the door to per-frame DDF special flags in general
=> More MBF21-related Dehacked fixes

source_files/edge/p_action.cc, source_files/edge/p_maputl.cc, source_files/edge/p_spec.cc
This fixes ComputeGaps not marking 0-height line 242 sectors as non-blocking (for rendering purposes), as well as a few other values
=> Height sector fixes

libraries/miniaudio/miniaudio_freeverb.h, source_files/ddf/ddf_reverb.cc, source_files/ddf/ddf_reverb.h, source_files/edge/am_map.cc, source_files/edge/con_con.cc, source_files/edge/i_ctrl.cc, source_files/edge/i_movie.cc, source_files/edge/i_sound.cc, source_files/edge/i_sound.h, source_files/edge/i_system.cc, source_files/edge/i_video.cc, source_files/edge/p_inter.cc, source_files/edge/p_user.cc, source_files/edge/render/gl/gl_backend.cc, source_files/edge/render/sokol/sokol_md2.cc, source_files/edge/render/sokol/sokol_mdl.cc, source_files/edge/render/sokol/sokol_units.cc, source_files/edge/s_blit.cc, source_files/edge/s_flac.cc, source_files/edge/s_m4p.cc, source_files/edge/s_midi.cc, source_files/edge/s_midi_ec.cc, source_files/edge/s_mp3.cc, source_files/edge/s_ogg.cc, source_files/edge/s_sound.cc
This addresses various miniaudio-related race conditions as identified by Clang TSAN, as well as tweaked the order of SDL subsystem shutdown and initialization checks. Incidentally cleaned up some Clang-related formatting warnings
=> Threading and SDL shutdown fixes

source_files/edge/e_main.cc, source_files/edge/i_movie.cc, source_files/edge/i_sound.cc, source_files/edge/i_sound.h, source_files/edge/m_menu.cc, source_files/edge/p_user.cc, source_files/edge/s_blit.cc, source_files/edge/s_flac.cc, source_files/edge/s_m4p.cc, source_files/edge/s_midi.cc, source_files/edge/s_midi_ec.cc, source_files/edge/s_mp3.cc, source_files/edge/s_music.cc, source_files/edge/s_ogg.cc, source_files/edge/s_sound.cc
This fixes a few issues:
- Uses miniaudio sound groups for sound/music volume split instead of setting each stream's audio independently
- Sounds will no longer be affected by underwater/vacuum/reverb filters in PC Speaker mode
- Quit response sound and associate loop on shutdown have been removed
=> Various audio fixes

ASanSuppress.txt, source_files/edge/am_map.cc, source_files/edge/i_movie.cc, source_files/edge/r_misc.cc, source_files/edge/s_blit.cc, source_files/edge/s_flac.cc, source_files/edge/s_m4p.cc, source_files/edge/s_midi.cc, source_files/edge/s_midi_ec.cc, source_files/edge/s_mp3.cc, source_files/edge/s_ogg.cc
Tracking down more TSAN/ASAN issues:
- Removed direct manipulating of Fluidlite state when pausing the game
- Fixed cleanup of various draw structures
- Removed unneeded adjustment of per-sound volume when ending sounds/songs
=> More leak/data race fixes

source_files/edge/render/gl/gl_md2.cc, source_files/edge/render/gl/gl_mdl.cc, source_files/edge/render/sokol/sokol_md2.cc, source_files/edge/render/sokol/sokol_mdl.cc
This fixes some issues with Sokol and model rendering:
- All supported models are now loaded as batches of triangles, eliminating the GL command behavior previously used to handle MD2s (legacy GL renderer still uses these). This will allow draw command merging and prevent issues with batching/flushing.
- Restored dynamic light passes for models as well as the "2D" MDL drawing function (for drawing models during the finale sequence)
=> Model rendering fixes

source_files/edge/hu_font.cc, source_files/edge/hu_font.h
Was having issues passing a potentially null pointer to construct a string_view with
=> Revert Font StringWidth method to use const char * again

source_files/edge/p_map.cc, source_files/edge/p_maputl.cc, source_files/edge/p_plane.cc, source_files/edge/p_spec.h, source_files/edge/sv_misc.cc
This is a more robust answer to my really old Doom E3M4 crusher fix
=> Update active plane mover destinations when recomputing gaps

CHANGELOG.md, edge_defs/scripts/coal_api.ec, source_files/edge/script/compat/lua_vm.cc, source_files/edge/vm_player.cc
-Add mapobject.render_view_tag(x, y, w, h, tag) and mapobject.render_view_tid(x, y, w, h, tid) to COAL
-Missing mapobject.query_tid(tid, whatinfo) from COALAPI
-Fix crash if we try and call a lua script from DDF(e.g. LUA_RUN_SCRIPT()), but are running COAL
=> LUA and COAL changes

ASanSuppress.txt, CHANGELOG.md, branding.cfg, source_files/edge/i_main.cc, source_files/edge/p_umapinfo.cc, source_files/edge/w_wad.cc
Updated the changelog/versioning files, and fixed the following issues:
- Memory leak from not freeing the return from SDL_GetBasePath
- UMAPINFO intertext/intertextsecret not being assigned properly (side effect from the Declarate parser migration)
- UMAPINFO levels that added an intertext without defining a backdrop having a black background instead of the default flat
=> More fixes

source_files/ddf/ddf_states.cc, source_files/dehacked/deh_weapons.cc
Fixed two issues observed when testing Dead Sea Scrolls:
- Demoted missing frame label from DDFError to DDFWarnError
- DSS's Dehacked patch is assigning frame numbers of zero to various Doom 2 things, presumably to prevent their usage in this WAD since it targets Ultimate Doom. This was causing a fatal error due to things like the boss brain not having a spawn state
- Chainsaws modified via Dehacked were still playing the SAWFUL sfx when attacking even if they were not actually using the chainsaw attack anymore (DSS uses the shotgun attack instead)
=> Dehacked tweaks

source_files/edge/p_setup.cc
One of the entries in Doom 2 In Rural Only, 11MUS, was being split into "11" and "MUS" by the scanner, causing issues when trying to change music mid-level
=> Fix accidental token splitting of MUSINFO entry names

source_files/edge/r_doomtex.cc
Issue seems to only affect doom format images when defined via TX markers. Initial testing looks good. Need to verify it doesn't break any font stuff possibly?
=> FIX: Doom format textures-as-flats images not tiling

source_files/edge/am_map.cc
This draws the automap background as black if no background image or color is defined via DDFSTYLE: this prevents non-black clear colors (like when draw culling is enabled) from becoming the automap background instead
=> Fix automap background color when not defined by the AUTOMAP style

source_files/edge/s_sound.cc
Fix BOSSMAN/ALWAYS_LOUD types of sounds; I think at one point I had added attenuation when we were playing with the linear vs. exponential falloff model, but now that we are using exponential again I have removed said attenuation
=> Tweak attenuation for "boss" category sounds

source_files/ddf/ddf_thing.cc, source_files/ddf/ddf_types.h, source_files/ddf/ddf_weapon.cc, source_files/ddf/ddf_weapon.h, source_files/dehacked/deh_weapons.cc, source_files/dehacked/deh_weapons.h
Rollup of some fixes for a few more Dehacked conversion issues:
- Added a mechanism to prevent weapons with a valid ammo type but an "ammo per shot" value of 0 from being converted to using the "noammo" ammunition type.
- Fixed "ammo per shot" value of 0 in patches from being applied properly
- For weapons modified via Dehacked to use a different ammo type than their default, added a "best effort" solution to give the correct amount of ammunition on weapon pickup. This replaces the hardcoded Doom behavior that ties ammunition pickup to specific sprites :/
=> More fixes for MBF21 weapon/ammo issues

source_files/edge/i_video.cc
Noticed this when testing legacy GL on a Pi 4, which only supports GL 3.1.
=> Fix GLAD version check for legacy GL

source_files/edge/m_menu.cc
We were not taking into account that the size of the text could be different for menu items with a custom SELECTED style. We need to recalculate the center each time.
=> Bugfix: Centering incorrect for SELECTED menu items

source_files/edge/con_con.cc, source_files/edge/p_user.cc
Noticed in places like Doom 2 In Rural Only MAP11 that the player was slowing down too much in high friction areas. Tweaked it to be somewhat closer to other ports.
=> Tweak movefactor for 'muddy' sectors

source_files/ddf/ddf_states.cc, source_files/edge/p_local.h, source_files/edge/p_mobj.cc, source_files/edge/p_weapon.cc
This adjusts the max thinker loop for mobjs/psprites to 64 which is still reasonable. Also added detection of truly empty states in DDF parsing (all frames are 0-tic with no actions and will loop back to its own beginning). These states will now have the tic count for their last frame set to 1 in order to reduce unnecessary looping.
=> Adjust thinker loops and handling of empty states
