source_files/edge/f_finale.cc
Assumes PFUB1 and PFUB2 are the same size.
=> Widescreen support for the damn bunny!

source_files/edge/p_action.cc
=> Properly Comment out weakness debug info

source_files/ddf/line.cc, source_files/ddf/line.h, source_files/edge/p_spec.cc
For breakable glass line types, among other things
=> New EFFECT_OBJECT for lines.ddf

CHANGELOG.txt, source_files/ddf/line.cc, source_files/ddf/line.h, source_files/edge/p_map.cc
=> Added BROKEN_TEXTURE field

CHANGELOG.txt, source_files/edge/p_action.cc
If we have CROUCH states for the player, they will be used when we crouch.
=> Crouching now uses CROUCH states

source_files/edge/m_menu.cc
Most of these are because we are missing a font in the styles ddf entry.
=> IDCLEV CTD fixed

CHANGELOG.txt, source_files/edge/r_doomtex.cc, source_files/edge/r_image.cc, source_files/edge/s_cache.cc, source_files/edge/w_sprite.cc
Commented out a lot of debug info that just clogs up debug.txt
=> Trimming debug.txt

source_files/edge/m_menu.cc
=> Additional check for Episode graphics

source_files/ddf/weapon.cc, source_files/ddf/weapon.h, source_files/edge/r_things.cc
Mainly for Heretic weapons support
=> New command: Y_ADJUST

source_files/edge/w_sprite.cc
=> Dont try to fix weapons

source_files/ddf/thing.cc, source_files/ddf/thing.h, source_files/edge/sv_play.cc
Lives, Score, Money and Experience for now.
=> Assign some arbitrary names to COUNTERxx

source_files/edge/w_sprite.cc
=> md2 weapons bug: Revert to old way

source_files/deh_edge/sounds.cc
Now creates a DDFSFX lump with only the used DEHEXTRA sfx entrys
=> DEHEXTRA: SFX fix

source_files/ddf/playlist.cc, source_files/ddf/playlist.h
Otherwise we break compatibility with any old mods that use it.
=> Added back CD music type

CMakeLists.txt, source_files/edge/f_interm.cc, source_files/edge/scanner.cc, source_files/edge/scanner.h, source_files/edge/umapinfo.cc, source_files/edge/umapinfo.h, source_files/edge/w_wad.cc
Just the bare minimum for now.
=> UMAPINFO support

source_files/ddf/playlist.cc, source_files/ddf/playlist.h, source_files/edge/w_wad.cc
Added support for the "music" key
=> UMAPINFO: music support

source_files/edge/hu_stuff.cc, source_files/edge/w_wad.cc
Added support for the levelname key
=> UMAPINFO: levelname support

source_files/edge/umapinfo.cc, source_files/edge/umapinfo.h, source_files/edge/w_wad.cc
Added support for
-endcast
-endbunny
-endgame
=> UMAPINFO: more keys supported

source_files/edge/f_interm.cc
=> Missing map name on intermission

source_files/edge/m_random.cc, source_files/edge/m_random.h, source_files/edge/p_action.cc, source_files/edge/p_enemy.cc, source_files/edge/p_local.h, source_files/edge/p_mobj.cc, source_files/edge/p_spec.cc
Mainly for Heretic:
A liquid is a flat defined in flats.ddf as having a splash effect.
MOBJs make splashes when stepping down into liquids, when a corpse falls onto a liquid, or when walking on liquid.
=> Initial MOBJ splash stuff

source_files/ddf/thing.cc, source_files/ddf/thing.h, source_files/edge/p_map.cc, source_files/edge/p_mobj.cc
-Renamed thing special PUSHY to SHOVEABLE
-Added new thing special NOSPLASH for things we don't want to make a splash i.e. a leaf or a ghost
=> MOBJ Splash and push tweaks

source_files/edge/p_local.h, source_files/edge/p_map.cc, source_files/edge/p_mobj.cc
=> More splash stuff

source_files/edge/m_menu.cc
Now we are comparing text instead of M_EPIxx graphic.
=> Finally fix the Episode select menu

source_files/edge/w_wad.cc
-intermusic
-intertextsecret
-partime
=> UMAPINFO: more keys added

source_files/edge/w_wad.cc
interbackdrop key wasn't quite right
=> UMAPINFO tweaks

source_files/edge/w_wad.cc
clear out values on certain conflicting maps
=> UMAPINFO: tweaks

source_files/edge/m_menu.cc
Text based menus for <Episode select> and <Difficulty select> were not working if the Main menu was using custom graphics
=> Text based menus bug

source_files/edge/w_flat.cc, source_files/edge/w_sprite.cc, source_files/edge/w_wad.cc, source_files/edge/w_wad.h, source_files/epi/utility.h
Also simplified W_GetListLumps, split into two functions (one for flats and one for sprites).
=> removed u32array_c and s32array_c, use std::vector instead.

CHANGELOG.txt, source_files/ddf/thing.cc, source_files/ddf/thing.h, source_files/edge/p_sight.cc
Which is how far a thing can see in map units.
=> New things.ddf command: SIGHT_DISTANCE

source_files/ddf/boom.cc
Fast and turbo generalized doors now play the fast sfx
=> Fix sfx for generalized doors

source_files/edge/p_setup.cc
This deals with the way we determine which sector a subsector should belong to.  When the only real seg(s) in a GL-NODE subsector are on self-ref linedefs (which have same sector on both sides), the new logic looks to grab the sector from a neighbor subsector (which in turn may grab it from another neighbor).
=> improved way self-referencing lines are handled by the level loader.

source_files/ddf/language.cc
Also updated DDF_SanitizeName() to do the same horrible stuff that DDF_CompareName() does -- ignore spaces and underscores.
=> fixed issue with DDF language IsValidRef() function.

source_files/edge/m_menu.cc
Caused by my latest styles.ddf tweaking.
=> Fix for save game crashing

source_files/edge/f_interm.cc
=> Intermission tweak

CHANGELOG.txt, source_files/edge/r_main.cc, source_files/edge/r_units.cc
Just for testing, not intended for the general public ;)
=> New CVAR: FogOfWar

source_files/edge/r_units.cc
Looks better when set to 1 at least
=> r_fogofwar tweak

CHANGELOG.txt, source_files/edge/m_menu.cc
=> "Read This!" fixed, finally

CHANGELOG.txt, source_files/edge/p_action.cc, source_files/edge/r_mdl.cc, source_files/edge/w_model.cc
Was processing weapon skins wrong.
=> Q1 mdl skin fix

source_files/edge/m_menu.cc, source_files/edge/m_option.cc
-Not applying colourmaps to menu headers/titles
-Using the wrong style for the episode menu
=> DDFSTYLES fixes

source_files/edge/p_enemy.cc, source_files/edge/p_spec.cc
No more splash objects while walking
=> Splash tweaks

source_files/edge/r_image.cc
in images.ddf. It was not centering vertically.
=> Fix for CROSSHAIR special

source_files/gl4es/src/gl/wrap/glstub.c
I also put in a PR with the change upstream
=> Fix issue with stub GLES2 functions checking env variable every call

CHANGELOG.txt, source_files/ddf/weapon.cc, source_files/edge/p_action.h, source_files/edge/p_weapon.cc
Behave identically as the things.ddf actions of the same name
- ZOOM
- SET_INVULNERABLE
- CLEAR_INVULNERABLE
- MOVE_FWD(num)
- MOVE_RIGHT(num)
- MOVE_UP(num)
- STOP
- TURN(angle)
- TURN_RANDOM(angle)
- MLOOK_TURN(angle)
=> WEAPONS.DDF: 10 new action commands

source_files/edge/p_mobj.cc
Don't make the sound if player is invulnerable
=> FALLPAIN_SOUND tweak

source_files/edge/r_things.cc
COAL hud.universal_y_adjust and WEAPONS.DDF Y_ADJUST now affect 3d models too
=> Y_ADJUST now affects models too

.github/workflows/cmake.yml
This switches the msys build action over to use ninja with is over a 2x speed bump for the build step
=> Switch to using ninja for msys build action

source_files/edge/f_interm.cc
=> Stats screen tweak

source_files/edge/f_interm.cc
=> Tweak: Stats screen

source_files/edge/e_player.cc, source_files/edge/p_user.cc
Hopefully this will mitigate it at least
=> INTERNAL ERROR: player has a removed attacker

source_files/edge/rad_trig.cc
Fixes tag grouping check, credits to Lobo for the find
=> Fix tag grouping check

edge_defs/scripts/coal_api.ec, edge_defs/scripts/coal_hud.ec, source_files/edge/hu_draw.cc, source_files/edge/hu_draw.h, source_files/edge/vm_hud.cc
-hud.get_image_width()
-hud.get_image_height()
=> New COAL functions to get image dimensions

CHANGELOG.txt, source_files/edge/vm_player.cc
This made it seem like health being picked up when player was at 100%
=> bug fix: health being rounded to 100 when it was slightly less.

CHANGELOG.txt, source_files/edge/vm_player.cc
This made it seem like green armour was being picked up when player was at 100%
=> bug fix: armour being rounded to 100 when it was slightly less.

source_files/edge/am_map.cc, source_files/edge/am_map.h, source_files/edge/defaults.h, source_files/edge/e_main.cc, source_files/edge/m_misc.cc, source_files/edge/m_option.cc
Initial commit. 
Later we might want to change the menu name/description or tweak the pulsing rate.
=> Automap: Keyed doors pulse

source_files/edge/am_map.cc
In Heretic the player symbol shown on the automap is a dagger.
=> Automap: different player symbol for Heretic and Blasphemer

source_files/dehacked/deh_patch.cc, source_files/edge/am_map.cc, source_files/edge/am_map.h, source_files/edge/defaults.h, source_files/edge/e_main.cc, source_files/edge/m_misc.cc, source_files/edge/m_option.cc
Accessibility Menu:
- Automap: Keyed Doors Pulse
- Automap: Keyed Doors Named
=> Separated "Pulsing" and "Named" AM door options

source_files/edge/con_main.cc, source_files/epi/filesystem.cc, source_files/epi/filesystem.h
Also adds the openhome console command to open the EC home directory in it
=> Adding FS_OpenDir to open an OS file browser 

.github/workflows/cmake.yml, cmake/Emscripten.cmake
=> Add web player to CI

CHANGELOG.txt, source_files/ddf/weapon.cc, source_files/ddf/weapon.h, source_files/edge/e_input.cc, source_files/edge/e_input.h, source_files/edge/e_player.cc, source_files/edge/e_player.h, source_files/edge/e_ticcmd.h, source_files/edge/m_misc.cc, source_files/edge/m_option.cc, source_files/edge/p_action.h, source_files/edge/p_weapon.cc, source_files/edge/p_weapon.h, source_files/edge/sv_play.cc
=> Weapons.ddf: 3rd and 4th attacks

source_files/ddf/weapon.cc, source_files/edge/p_weapon.cc
-now pressing the keys actually work ;)
-clarified some error messages
=> More attacks stuff

edge_defs/scripts/styles.ddf
Was slightly too big after the recent font changes
=> Tweak: Load/Save text out of bounds

source_files/edge/script/compat/lua_core.cc, source_files/edge/w_wad.cc
=> Add support for LUAHUDS in wad files, closes #615

edge_base/blasphemer/scripts/lua/edge_hud.lua, edge_base/harmony/scripts/lua/edge_hud.lua, edge_base/heretic/scripts/lua/edge_hud.lua, edge_defs/scripts/lua/edge_hud.lua
=> Bug: Wrong armour shown on HUD

CHANGELOG.md, CMakeLists.txt, libraries/tracy/edge_profiling.h, source_files/edge/CMakeLists.txt, source_files/edge/con_con.cc, source_files/edge/e_main.cc, source_files/edge/i_ctrl.cc, source_files/edge/i_video.cc, source_files/edge/n_network.cc, source_files/edge/p_blockmap.cc, source_files/edge/r_render.cc, source_files/edge/r_things.cc, source_files/edge/r_units.cc, source_files/edge/script/compat/lua_vm.cc
Also adds draw metrics that can be displayed with `debug_fps 3`
=> Adding support for Tracy profiler, closes #559

source_files/edge/script/compat/lua_player.cc
=> LUAHUDS: Get more info from our mobj

source_files/edge/script/compat/lua_player.cc
-Return weapon name for benefit
-Use lua_setfield
=> More luahud function tweaks

source_files/edge/script/compat/lua_player.cc
-new function: mapobject.weapon_info(maxdistance)
-get some more info from our mobjs
=> Luahuds work

source_files/edge/script/compat/lua_player.cc
take into account all factors that change how much ammo we get
=> Lua benefits tweak

source_files/edge/script/compat/lua_hud.cc
hud.game_skill():
Returns a number from 0 to 4 corresponding to the current skill level
=> LUA_HUDS: New function

source_files/edge/e_player.cc, source_files/edge/e_player.h, source_files/edge/p_spec.cc, source_files/edge/p_user.cc, source_files/edge/script/compat/lua_player.cc, source_files/edge/sv_play.cc
3 new functions that return a table with info:
-game.info()
-map.info()
-sector.info()
=> New lua-only hud functions

source_files/epi/filesystem.cc
sys/stat.h needed to be included on MinGW in filesystem.cc
=> Fix compilation on MinGW Clang.

CHANGELOG.md, docs/changelogs/137.txt, edge_defs/scripts/coal_api.ec, source_files/edge/script/compat/lua_hud.cc, source_files/edge/vm_hud.cc
New function hud.lookup_LDF(languageEntry ) which will return the language.ldf entry.
=> COALHUDS/LUAHUDS: new function hud.lookup_LDF(languageEntry )

edge_defs/scripts/language.ldf, source_files/edge/f_interm.cc
=> Localization

source_files/edge/rad_pars.cc
Show the line number with the issue
=> QOL for debugging RTS

edge_defs/scripts/coal_api.ec, source_files/edge/hu_draw.cc, source_files/edge/hu_draw.h, source_files/edge/script/compat/lua_hud.cc, source_files/edge/vm_hud.cc
=> Initial attempt at new hud.get_text_width()

CHANGELOG.md, edge_defs/scripts/coal_api.ec, source_files/edge/vm_hud.cc
Updated changelog.
Added hud.game_skill() for coal too.
=> tweak for next release

CHANGELOG.md, source_files/edge/r_image.cc, source_files/edge/r_image.h, source_files/edge/w_flat.cc
FIRST and LAST fields in anims.ddf now work with TX textures.
=> FIRST and LAST fields in anims.ddf now work with TX textures

source_files/edge/script/compat/lua_player.cc
=> Tweak to sector.fog_colour()

source_files/edge/script/compat/lua_hud.cc, source_files/edge/vm_hud.cc
Too extreme to abort the whole game. Especially when we will fall back to a default font if there is an issue anyway.
=> Hud scripting: downgraded FatalError to nothing

source_files/edge/rad_trig.cc
We were only processing the first script found, not all of them.
=> Bugfix: multiple RTS with the same tag

CHANGELOG.md, source_files/edge/hu_stuff.cc
=> Stacked messages tweak

CHANGELOG.md, source_files/edge/m_cheat.cc, source_files/edge/p_spec.cc
Keylocked doors and Cheat messages moved to middle of the screen (same as "Found a Secret" message)
=> Important Messages tweak

CHANGELOG.md, source_files/edge/p_action.cc, source_files/edge/rad_trig.cc
-Added dropshadow support to RTS menus
-Reverted tracer smoke randomizer
=> Dropshadows and reverts

docs/mapping/EdgeC_UDB_Config/Includes/EdgeC_misc.cfg, source_files/edge/am_map.cc
-Automap zooming tweaks
-Enable Z slope editing in our UDB config
=> Automap zooming tweaks

source_files/ddf/ddf_thing.cc, source_files/edge/p_action.cc, source_files/edge/p_action.h, source_files/edge/p_enemy.cc, source_files/edge/p_local.h, source_files/edge/p_setup.cc, source_files/edge/p_sight.cc
=> New Friendly logic

source_files/edge/r_render.cc
Caveman hack for PD2map05 bridge and glitchy midtex
=> Unga Bunga.

source_files/edge/p_action.cc
=> Make SET_SCALE() handle models too

source_files/edge/f_finale.cc
For those texts that are just too many lines to fit on screen.
=> Rough autoscaling for intermission texts

source_files/edge/f_finale.cc
=> Autoscale intermission tweak

source_files/edge/con_con.cc, source_files/edge/con_main.h, source_files/edge/i_ctrl.cc, source_files/edge/i_video.cc
This can also be extended to when menus are active when we can actually have the menu elements themselves be clickable
=> Release mouse cursor when console active

source_files/edge/r_render.cc, source_files/edge/r_things.cc
Some small fixes for a couple of warnings I noticed when building with GCC
=> Fix some recent compilation warnings

source_files/edge/render/sokol/sokol_backend.cc
Hooked up clear color to sokol renderer
=> Sokol: Hook up clear color

CHANGELOG.md, source_files/edge/f_interm.cc
Unless there is a level camera setup.
=> Stopped looping SFX still playing on intermission screen

source_files/edge/i_movie.cc
Fixes https://github.com/edge-classic/EDGE-classic/issues/826
=> Fix MPEG playback on Sokol render paths

libraries/fluidlite/src/fluid_defsfont.c, libraries/fluidlite/src/fluid_synth.c, libraries/fluidlite/src/fluid_voice.c
Pulls in fixes for various loop and channel handling but also fixes a CTD upon loading Patch93's SC-55 soundfont
=> Fluidlite fixes

source_files/edge/am_map.cc, source_files/edge/con_con.cc, source_files/edge/con_main.cc, source_files/edge/con_main.h, source_files/edge/e_main.cc, source_files/edge/g_game.cc, source_files/edge/hu_draw.cc, source_files/edge/i_ctrl.cc, source_files/edge/i_system.cc, source_files/edge/m_cheat.cc, source_files/edge/m_menu.cc, source_files/edge/p_inter.cc, source_files/edge/p_spec.cc, source_files/edge/p_telept.cc, source_files/edge/rad_act.cc
This cleans up a lot of cruft and redundancy with the console and ENDOOM drawing functions; it also tries to batch them a little better although not to quite the extent that the recent automap updates did.
=> ENDOOM and Console Updates

source_files/edge/r_colormap.cc, source_files/edge/r_render.cc, source_files/edge/r_shader.cc, source_files/edge/r_shader.h, source_files/edge/r_things.cc, source_files/edge/r_units.h, source_files/edge/render/gl/gl_md2.cc, source_files/edge/render/gl/gl_mdl.cc, source_files/edge/render/gl/gl_units.cc, source_files/edge/render/sokol/sokol_md2.cc, source_files/edge/render/sokol/sokol_mdl.cc, source_files/edge/render/sokol/sokol_units.cc
=> Enforce BlendingMode as an runit param

source_files/edge/i_main.cc, source_files/edge/w_epk.cc, source_files/epi/epi_filesystem.cc, source_files/epi/epi_filesystem.h
Addresses https://github.com/edge-classic/EDGE-classic/issues/835
=> Remove getting/setting of program working directory

source_files/dehacked/deh_frames.cc, source_files/dehacked/deh_weapons.cc, source_files/dehacked/deh_weapons.h
This fixes the flash state when using A_FireCGun to reference the currently processing weapon instead of the chaingun
=> A_FireCGun fix

edge_defs/scripts/attacks.ddf, source_files/ddf/ddf_thing.cc, source_files/dehacked/deh_frames.cc, source_files/edge/p_action.cc
This updates A_Mushroom to align with MBF behavior
=> A_Mushroom updates

source_files/edge/bot_nav.cc, source_files/edge/p_blockmap.cc, source_files/edge/p_map.cc, source_files/edge/p_maputl.cc, source_files/edge/p_setup.cc, source_files/edge/p_sight.cc, source_files/edge/r_bsp.cc, source_files/edge/r_defs.h, source_files/edge/r_misc.cc, source_files/edge/r_state.h
Fixes https://github.com/edge-classic/EDGE-classic/issues/853 and the first map of LegendsWAD Episode 3; likely other issues
=> Fix method of determining what sectors a thing is touching

source_files/ddf/ddf_thing.cc, source_files/ddf/ddf_thing.h, source_files/edge/con_con.cc, source_files/edge/con_main.cc
Addresses https://github.com/edge-classic/EDGE-classic/issues/791
Pauses gameplay when console active and adds the following console commands:
- move \<x\> \<y\>
- spawn \<name or id\> \<x\> \<y\>
- god
- noclip
=> Pause gameplay when console toggled; add new commands

ASanSuppress.txt, libraries/miniaudio/miniaudio.cc, source_files/edge/con_con.cc, source_files/edge/e_main.cc, source_files/edge/hu_draw.cc, source_files/edge/hu_font.cc, source_files/edge/hu_font.h, source_files/edge/i_system.cc, source_files/edge/im_data.cc, source_files/edge/r_colormap.cc, source_files/edge/r_misc.cc, source_files/edge/s_midi.cc, source_files/edge/s_midi_ec.cc, source_files/edge/s_sound.cc
This fixes a goof with the recent sprite clip fix as well as addresses some of the leaks identified by ASAN
=> CTD and memory leak fixes

source_files/edge/am_map.cc, source_files/edge/bot_think.cc, source_files/edge/con_con.cc, source_files/edge/con_main.cc, source_files/edge/dm_state.h, source_files/edge/hu_font.cc, source_files/edge/p_tick.cc, source_files/edge/r_render.cc, source_files/edge/r_sky.cc, source_files/edge/r_things.cc, source_files/edge/render/gl/gl_md2.cc, source_files/edge/render/gl/gl_mdl.cc, source_files/edge/render/sokol/sokol_md2.cc, source_files/edge/render/sokol/sokol_mdl.cc, source_files/edge/script/compat/lua_hud.cc, source_files/edge/vm_hud.cc
This tweaks the method by which the game is paused if the console active as well as fixes IMAGE type font loading that was borked due to the recent sprite clip fixes
=> Console and HUD font fixes

source_files/edge/p_mobj.cc, source_files/edge/script/compat/lua_player.cc
Moved the TID/TAG removal code from RemoveMobjFromList() to RemoveMapObject() to make sure to trip DDF action "#REMOVE", which was not triggering otherwise.
=> Bug: TID/TAG removal not happening for #REMOVEd mobjs

source_files/dehacked/deh_things.cc, source_files/edge/p_mobj.cc, source_files/edge/p_plane.cc, source_files/edge/render/gl/gl_md2.cc, source_files/edge/render/gl/gl_mdl.cc, source_files/edge/render/sokol/sokol_md2.cc, source_files/edge/render/sokol/sokol_mdl.cc
This fixes angle interpolation for models, as well as updating MapObjectSetDirectionAndSpeed to account for the new (lower) kMaximumMove value
=> Fixes for model interpolation and map object angle/aiming

CMakeLists.txt, source_files/edge/i_video.cc
Some things didn't pop because the local cache wasn't cleared first
=> Fix stragglers from previous PR

source_files/edge/hu_draw.cc
Introduced when the fonts were broken out into separate classes and such
=> HUDDrawText fix

source_files/edge/p_mobj.cc, source_files/edge/p_user.cc
Fixes for determining if friction or carry forces from touching sectors affect a mobj
=> Fixes for friction/carry checks

source_files/edge/r_doomtex.cc
Prevents potential artifacts in psprites, etc
=> Add opacity check for non-flat image tiling

source_files/edge/render/gl/gl_md2.cc, source_files/edge/render/sokol/sokol_md2.cc
Remove now-unneeded variables/values, some of which were fouling up Sokol's MD2 rendering
=> Cleanup from previous NPOT merge
